FROM node:18-alpine

# Set metadata
LABEL maintainer="dev@techquestltd.com"
LABEL version="1.0"
LABEL description="Development image for Pan-African application"

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose port for the development server
EXPOSE 5173

# Command to start the development server
CMD ["npm", "run", "dev", "--", "--host"]
